version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - "3002:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - ./backups:/backups  # Backup directory
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo  # Fixed typo (was DATABASE)
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backups:/backups
      - ./daily-backup.sh:/etc/periodic/daily/backup
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1  # Allows connection to any MySQL server
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
